File JSON e JS
zanardigit/bookreplacer pull request #1
Opened 2021-03-21 10:51 UTC by ConteEmanuele

2021-03-21 12:58 UTC, zanardigit approved these changes
Buon inizio. Ti ho fatto alcuni appunti minori ma ti accetto comunque la PR, le modifiche suggerite andranno nella prossima PR. Con l'occasione ti chiedo di dare una occhiata ai `template` in modo da semplificare la costruzione degli elementi:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

2021-03-21 12:58 UTC, zanardigit commented on js/prenotazioni.js
> +    let array = data;
Questa riga mi sembra superflua.

2021-03-21 12:58 UTC, zanardigit commented on js/prenotazioni.js
> +        azione( data[i].stato, row, i);
Questi metodi vanno benissimo, ma li nominerei in modo da rendere più evidente a cosa servono. Es. `renderizzaImmagini`.

2021-03-28 14:02 UTC, zanardigit requested changes

2021-03-28 14:02 UTC, zanardigit commented on js/prenotazioni.js
> +let tbody = document.querySelector("tbody");
Dove sono definiti questi template? Non li vedo nella PR. Il resto è ok!

2021-03-28 17:12 UTC, ConteEmanuele commented
Ok grazie. Chiedo scusa per il codice del template, deve essermi sfuggito
visto che l'ho scritto su una copia del progetto, comunque ora lo ho
aggiunto mi faccia sapere se si vede.

Il giorno dom 28 mar 2021 alle ore 16:02 Francesco Abeni <
***@***.***> ha scritto:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In js/prenotazioni.js
> <https://github.com/zanardigit/bookreplacer/pull/1#discussion_r602883394>:
>
> > @@ -0,0 +1,126 @@
>
> +let tbody = document.querySelector("tbody");
>
>
> Dove sono definiti questi template? Non li vedo nella PR. Il resto è ok!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zanardigit/bookreplacer/pull/1#pullrequestreview-622750915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APJLJPUDM3LFLYPPDTACB2TTF5AHNANCNFSM4ZRNWS3A>
> .
>

2021-03-29 06:53 UTC, merged

2021-03-29 06:53 UTC, zanardigit commented
Perfetto! Nessun problema.